### ISSUE TITLE
QWindow adds infinite vertical scroll at in Quasar projects with :height="640"

### ISSUE THREAD

**Issue by Sfinx** [quasarframework/quasar-ui-qwindow#17]
Adding QWindow to stock quasar project adds some buggy vertical scrolling

1. Create empty quasar project (quasar create, bla-bla)
2. Add QWindow (quasar ext add @quasar/qwindow)
3. Issue 'quasar dev' and open page in desktop and mobile browsers (checked at Android)
4. Check that page is not scrolled in any direction
5. Add to src/layouts/MainLayout.vue :

```
<q-window
      v-model="show"
      title="Title"
      :actions="['pin', 'close']"
      bring-to-front-after-drag
      :start-x="50"
      :start-y="50"
      :height="640"
      :width="480"
      :content-class="$q.dark.isActive ? 'bg-grey-8' : 'bg-grey-3'"
    >
      <div class="q-pa-lg fit">
          <q-btn glossy class="bg-red text-white" label="Btn" />
        </div>
    </q-window> 
```
6. Observe normal behavior at desktop browser and infinite vertical scroll at mobile one

**Expected behavior**
No vertical scroll must be present at the page

 - OS: Ubuntu with latest Chrome/Firefox

**Comment by Sfinx** [comment]
Any news at this issue ? Checked beta0.0.4, bug is still present. Additional information:

- bug is present at **usual desktop browsers** too (checked at latest Firefox/Chrome)
- the bug is 100% reproducible when adding the :height="640" so mininal code became:

```
  <q-window
      v-model="show"
      :height="640"
    />
```

the v-model show value do not matter, I'm using false

**Comment by hawkeye64** [comment]
@Sfinx I have not been able to reproduce it. Can you try this codepen and get the issue to occur?
https://codepen.io/Hawkeye64/pen/LYREZyJ?editors=101

**Comment by Sfinx** [comment]
@hawkeye64 Codepen will not work - you must add QWindow with height to stock initial Quasar project. I've made one for you - please use attached file, untar it, issue: 'cd q, quasar dev'

[q.zip](https://github.com/quasarframework/quasar-ui-qwindow/files/5610744/q.zip)

**Comment by hawkeye64** [comment]
@Sfinx I am not getting the same results as you. First, I had to make the QWindow visible (from Chrom Dev Tools). Then I "pinned" it. There is no coloring to the QWindow, so it's not really visible. When pinned, it pushed the Quasar logo down. Which increased the height of the page, that's it. 
A couple of things. I notice you are adding it to the layout. Try it on a page. It needs a parent to control it's width and height, or do that with styles (otherwise it's 100% width and height). Add some more options, so at least it has color and can be visible.
In this image, you can see I got no scollbars:
![image](https://user-images.githubusercontent.com/10262924/100550334-7bb4c780-3236-11eb-9d5b-51d447c65b03.png)

**Comment by Sfinx** [comment]
Thanks for reply ! Moving to q-page changes nothing. Please see my screenshot. The scrollbar that appears to the right - scrolls down to infinite in my case. Same project, just moved q-window to q-page-container section

![q](https://user-images.githubusercontent.com/1393676/100555868-09300000-32a7-11eb-84bd-19be49652d7e.png)

**Comment by Sfinx** [comment]
Oops, did not deleted the q-window from layout but it still changes nothing. In my case the q-window top value in Elements is increasing infinitely when scrolling down

**Comment by Sfinx** [comment]
Found why you can't reproduce the issue ;) The bug is reproducible only when height of the window is bigger than the layout height. At your case the window is fully fit at the layout but in my case the bottom of the window is located out of the layout bottom and infinite scroll appears only at this case. Thanks anyway as at least I can make workaround for this checking that window must not located outside of the layout.

**Comment by Sfinx** [comment]
And to reproduce the bug just grab the header of window by mouse and move it to the bottom until end of the window will not come out of the main layout and you will be able to enjoy infinite scrollbar show

**Comment by hawkeye64** [comment]
That's why I said 
> It needs a parent to control it's width and height, or do that with styles (otherwise it's 100% width and height).

If it starts pushing the layout down, then the css will make it grow. If you don't have a container to fit it in, then it's being used wrong. So, putting it somewhere on a page will make it 100% height, which will push the layout/page down, which then pushes QWindow down in a vicious circle. Probably shouild have done it the other way around like QScrollArea :man_shrugging:

**Comment by Sfinx** [comment]
Oh, so it is not a bug but intended behavior ? Then closing. Can you please advise exactly how to fix this "q" sample project to not have this infinite scrolling ? I've tried q-page/div with exact width/height set with no success. Thanks for help !
